// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: digimons.proto

package digimons

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Digiquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Digiquest) Reset() {
	*x = Digiquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_digimons_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Digiquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Digiquest) ProtoMessage() {}

func (x *Digiquest) ProtoReflect() protoreflect.Message {
	mi := &file_digimons_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Digiquest.ProtoReflect.Descriptor instead.
func (*Digiquest) Descriptor() ([]byte, []int) {
	return file_digimons_proto_rawDescGZIP(), []int{0}
}

func (x *Digiquest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Digisponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Img   string `protobuf:"bytes,2,opt,name=img,proto3" json:"img,omitempty"`
	Level string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *Digisponse) Reset() {
	*x = Digisponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_digimons_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Digisponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Digisponse) ProtoMessage() {}

func (x *Digisponse) ProtoReflect() protoreflect.Message {
	mi := &file_digimons_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Digisponse.ProtoReflect.Descriptor instead.
func (*Digisponse) Descriptor() ([]byte, []int) {
	return file_digimons_proto_rawDescGZIP(), []int{1}
}

func (x *Digisponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Digisponse) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *Digisponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

var File_digimons_proto protoreflect.FileDescriptor

var file_digimons_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x73, 0x22, 0x1f, 0x0a, 0x09, 0x44, 0x69,
	0x67, 0x69, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x0a, 0x44,
	0x69, 0x67, 0x69, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x6d, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x32, 0x40, 0x0a, 0x07, 0x44, 0x69, 0x67, 0x69, 0x6e, 0x66, 0x6f,
	0x12, 0x35, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x13, 0x2e, 0x64, 0x69, 0x67,
	0x69, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x69, 0x67, 0x69, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x69, 0x67, 0x69, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_digimons_proto_rawDescOnce sync.Once
	file_digimons_proto_rawDescData = file_digimons_proto_rawDesc
)

func file_digimons_proto_rawDescGZIP() []byte {
	file_digimons_proto_rawDescOnce.Do(func() {
		file_digimons_proto_rawDescData = protoimpl.X.CompressGZIP(file_digimons_proto_rawDescData)
	})
	return file_digimons_proto_rawDescData
}

var file_digimons_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_digimons_proto_goTypes = []interface{}{
	(*Digiquest)(nil),  // 0: digimons.Digiquest
	(*Digisponse)(nil), // 1: digimons.Digisponse
}
var file_digimons_proto_depIdxs = []int32{
	0, // 0: digimons.Diginfo.search:input_type -> digimons.Digiquest
	1, // 1: digimons.Diginfo.search:output_type -> digimons.Digisponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_digimons_proto_init() }
func file_digimons_proto_init() {
	if File_digimons_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_digimons_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Digiquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_digimons_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Digisponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_digimons_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_digimons_proto_goTypes,
		DependencyIndexes: file_digimons_proto_depIdxs,
		MessageInfos:      file_digimons_proto_msgTypes,
	}.Build()
	File_digimons_proto = out.File
	file_digimons_proto_rawDesc = nil
	file_digimons_proto_goTypes = nil
	file_digimons_proto_depIdxs = nil
}
